language: node_js
cache:
  yarn: true
  directories:
  - node_modules
node_js:
  - '8'
script: "npm t"
# Send coverage report to coveralls.io
# after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
notifications:
  slack: virtuous-coding:qsxYU1TMf0AAzcCALg4C8t17
  email: false
branches:
  only:
  - master
