language: node_js
node_js:
- "10"
script: jest --coverage --coverageReporters=text-lcov | coveralls
notifications:
  slack: virtuous-coding:qsxYU1TMf0AAzcCALg4C8t17
  email: false
branches:
  only:
  - master
