language: node_js
cache:
  yarn: true
  directories:
  - node_modules
node_js:
  - '8'
script: "npm run cover"
# Send coverage report to coveralls.io
after_script: "./sendReports.js"
notifications:
  slack: virtuous-coding:qsxYU1TMf0AAzcCALg4C8t17
  email: false
branches:
  only:
  - master
