export const CONDUCTOR_PUSH = 'CONDUCTOR_PUSH';
export const CONDUCTOR_POP = 'CONDUCTOR_POP';
export const CONDUCTOR_REPLACE = 'CONDUCTOR_REPLACE';
export const CONDUCTOR_RESET = 'CONDUCTOR_RESET';
export const CONDUCTOR_UPDATE = 'CONDUCTOR_UPDATE';
